apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpinfo
  labels:
    app: phpinfo
spec:
  selector:
    matchLabels:
      app: phpinfo
  replicas: 1
  template:
    metadata:
      labels:
        app: phpinfo
    spec:
      containers:
      - name: phpinfo
        image: wamoco/phpinfo
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpinfo
spec:
  selector:
    app: phpinfo
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: phpinfo
spec:
  rules:
  - host: $DOMAIN
    http:
      paths:
      - path: /
        backend:
          serviceName: phpinfo
          servicePort: 80
